//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Communicateoutlinepanel_prefab
    {
        public const string BundleName = "communicateoutlinepanel_prefab";
        public const string COMMUNICATEOUTLINEPANEL = "CommunicateOutlinePanel";
    }
    public class Getinfornationpanel_prefab
    {
        public const string BundleName = "getinfornationpanel_prefab";
        public const string GETINFORMATIONPANEL = "GetInformationPanel";
    }
    public class Homevisitcontentpanel_prefab
    {
        public const string BundleName = "homevisitcontentpanel_prefab";
        public const string HOMEVISITCONTENTPANEL = "HomeVisitContentPanel";
    }
    public class Homevisitformpanel_prefab
    {
        public const string BundleName = "homevisitformpanel_prefab";
        public const string HOMEVISITFORMPANEL = "HomeVisitFormPanel";
    }
    public class Homevisitroutepanel_prefab
    {
        public const string BundleName = "homevisitroutepanel_prefab";
        public const string HOMEVISITROUTEPANEL = "HomeVisitRoutePanel";
    }
    public class Knowledgeexampanel_prefab
    {
        public const string BundleName = "knowledgeexampanel_prefab";
        public const string KNOWLEDGEEXAMPANEL = "KnowledgeExamPanel";
    }
    public class Mainpanel_prefab
    {
        public const string BundleName = "mainpanel_prefab";
        public const string MAINPANEL = "MainPanel";
    }
    public class Maskpanel_prefab
    {
        public const string BundleName = "maskpanel_prefab";
        public const string MASKPANEL = "MaskPanel";
    }
    public class Onvisitpanel_prefab
    {
        public const string BundleName = "onvisitpanel_prefab";
        public const string ONVISITPANEL = "OnVisitPanel";
    }
    public class Recordsheetpanel_prefab
    {
        public const string BundleName = "recordsheetpanel_prefab";
        public const string RECORDSHEETPANEL = "RecordSheetPanel";
    }
    public class Submittestpanel_prefab
    {
        public const string BundleName = "submittestpanel_prefab";
        public const string SUBMITTESTPANEL = "SubmitTestPanel";
    }
    public class Testbriefpanel_prefab
    {
        public const string BundleName = "testbriefpanel_prefab";
        public const string TESTBRIEFPANEL = "TestBriefPanel";
    }
    public class Testreportpanel_prefab
    {
        public const string BundleName = "testreportpanel_prefab";
        public const string TESTREPORTPANEL = "TestReportPanel";
    }
    public class Title
    {
        public const string BundleName = "title";
        public const string JUDGETITLE = "JudgeTitle";
        public const string MULTIPLETITLE = "MultipleTitle";
        public const string OUTLINETITLE = "OutlineTitle";
        public const string SCOREREPORT = "ScoreReport";
        public const string SINGLETITLE = "SingleTitle";
        public const string TOGOUTLINE = "TogOutline";
    }
    public class Toppanel_prefab
    {
        public const string BundleName = "toppanel_prefab";
        public const string TOPPANEL = "TopPanel";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
        public const string CLOTHESPANEL = "ClothesPanel";
    }
}
