//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string A = "a";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "assetobj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "assetobj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "assetobj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string B = "b";
    }
    public class Buttonpanel_prefab
    {
        public const string BundleName = "buttonpanel_prefab";
        public const string BUTTONPANEL = "buttonpanel";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string C = "c";
    }
    public class Clothespanel_prefab
    {
        public const string BundleName = "clothespanel_prefab";
        public const string CLOTHESPANEL = "clothespanel";
    }
    public class Communicateoutlinepanel_prefab
    {
        public const string BundleName = "communicateoutlinepanel_prefab";
        public const string COMMUNICATEOUTLINEPANEL = "communicateoutlinepanel";
    }
    public class Homevisitcontentpanel_prefab
    {
        public const string BundleName = "homevisitcontentpanel_prefab";
        public const string HOMEVISITCONTENTPANEL = "homevisitcontentpanel";
    }
    public class Homevisitformpanel_prefab
    {
        public const string BundleName = "homevisitformpanel_prefab";
        public const string HOMEVISITFORMPANEL = "homevisitformpanel";
    }
    public class Homevisitroutepanel_prefab
    {
        public const string BundleName = "homevisitroutepanel_prefab";
        public const string HOMEVISITROUTEPANEL = "homevisitroutepanel";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string IMAGEPREFABA = "imageprefaba";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string IMAGEPREFABB = "imageprefabb";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string IMAGEPREFABC = "imageprefabc";
    }
    public class Knowledgeexampanel_prefab
    {
        public const string BundleName = "knowledgeexampanel_prefab";
        public const string KNOWLEDGEEXAMPANEL = "knowledgeexampanel";
    }
    public class Mainpanel_prefab
    {
        public const string BundleName = "mainpanel_prefab";
        public const string MAINPANEL = "mainpanel";
    }
    public class Multipletitle_prefab
    {
        public const string BundleName = "multipletitle_prefab";
        public const string MULTIPLETITLE = "multipletitle";
    }
    public class Onvisitpanel_prefab
    {
        public const string BundleName = "onvisitpanel_prefab";
        public const string ONVISITPANEL = "onvisitpanel";
    }
    public class Recordsheetpanel_prefab
    {
        public const string BundleName = "recordsheetpanel_prefab";
        public const string RECORDSHEETPANEL = "recordsheetpanel";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Scorereport_prefab
    {
        public const string BundleName = "scorereport_prefab";
        public const string SCOREREPORT = "scorereport";
    }
    public class Singletitle_prefab
    {
        public const string BundleName = "singletitle_prefab";
        public const string SINGLETITLE = "singletitle";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Submittestpanel_prefab
    {
        public const string BundleName = "submittestpanel_prefab";
        public const string SUBMITTESTPANEL = "submittestpanel";
    }
    public class Testgoalpanel_prefab
    {
        public const string BundleName = "testgoalpanel_prefab";
        public const string TESTGOALPANEL = "testgoalpanel";
    }
    public class Testreportpanel_prefab
    {
        public const string BundleName = "testreportpanel_prefab";
        public const string TESTREPORTPANEL = "testreportpanel";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "textureexample1";
    }
    public class Uibasicpanel_prefab
    {
        public const string BundleName = "uibasicpanel_prefab";
        public const string UIBASICPANEL = "uibasicpanel";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMULTIPANEL = "uimultipanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPANELWITHIMAGEPREFAB = "uipanelwithimageprefab";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
    }
    public class Uistackpanel1_prefab
    {
        public const string BundleName = "uistackpanel1_prefab";
        public const string UISTACKPANEL1 = "uistackpanel1";
    }
    public class Uistackpanel2_prefab
    {
        public const string BundleName = "uistackpanel2_prefab";
        public const string UISTACKPANEL2 = "uistackpanel2";
    }
}
